// projects-data.js - Complete Project Portfolio for Luigie Martin (@dxlmartin00)

const PROJECTS_DATA = [
  {
    id: "spamblock",
    title: "SpamBlock",
    category: "mobile",
    language: "Kotlin",
    stars: 0,
    featured: true,
    description: "An intelligent Android utility designed to detect and intercept spam phone calls and unsolicited SMS messages in real time using rule-based filtering and pattern recognition.",
    tech: ["Kotlin", "Android SDK", "Telephony API", "Room DB", "Material 3"],
    githubUrl: "https://github.com/dxlmartin00/SpamBlock",
    demoUrl: null,
    badge: "MOBILE APP",
    icon: "🛡️",
    highlights: ["Real-time SMS & Call Interception", "Custom Blacklist/Whitelist", "Local SQLite database storage"]
  },
  {
    id: "proftrack",
    title: "ProfTrack",
    category: "web",
    language: "TypeScript",
    stars: 0,
    featured: true,
    description: "A fullstack faculty performance monitoring and scheduling platform enabling academic institutions to evaluate instructor efficiency, class schedules, and student performance metrics.",
    tech: ["TypeScript", "React", "Node.js", "Express", "Tailwind CSS", "REST API"],
    githubUrl: "https://github.com/dxlmartin00/ProfTrack",
    demoUrl: null,
    badge: "FULLSTACK",
    icon: "📊",
    highlights: ["Faculty Evaluation Workflows", "Dynamic Schedule Management", "Analytics & Reporting Dashboard"]
  },
  {
    id: "webquiz",
    title: "WebQuiz",
    category: "web",
    language: "TypeScript",
    stars: 0,
    featured: true,
    description: "An interactive, web-based examination and quiz platform built with TypeScript, featuring real-time question timers, instant score evaluation, and responsive design.",
    tech: ["TypeScript", "Next.js / React", "CSS Modules", "Vercel Deploy"],
    githubUrl: "https://github.com/dxlmartin00/WebQuiz",
    demoUrl: "https://webquiz-drab.vercel.app",
    badge: "LIVE DEMO",
    icon: "⚡",
    highlights: ["Live on Vercel", "Dynamic Timer & Scoring", "Mobile-optimized Quiz Flow"]
  },
  {
    id: "fecalvision",
    title: "FecalVision",
    category: "ai",
    language: "Dart",
    stars: 0,
    featured: true,
    description: "A mobile diagnostic and computer vision tool that leverages machine learning image classification to assist healthcare or veterinary screening through smartphone camera feeds.",
    tech: ["Dart", "Flutter", "Computer Vision", "TensorFlow Lite", "Image Processing"],
    githubUrl: "https://github.com/dxlmartin00/FecalVision",
    demoUrl: null,
    badge: "AI / COMPUTER VISION",
    icon: "🔬",
    highlights: ["On-device ML Model Inference", "Live Camera Feed Analysis", "Diagnostic Reporting Engine"]
  },
  {
    id: "qrotc",
    title: "QROTC",
    category: "web",
    language: "JavaScript",
    stars: 0,
    featured: true,
    description: "An automated attendance and cadet management system built for military science and university ROTC units using high-speed QR code scanning and roster synchronization.",
    tech: ["JavaScript", "HTML5/CSS3", "QR Scanner API", "LocalStorage", "Node.js"],
    githubUrl: "https://github.com/dxlmartin00/QROTC",
    demoUrl: null,
    badge: "CAMPUS TECH",
    icon: "🎖️",
    highlights: ["Instant QR-based Attendance", "Cadet Directory Management", "CSV Attendance Export"]
  },
  {
    id: "cs-assistant",
    title: "CS_Assistant",
    category: "ai",
    language: "Python",
    stars: 0,
    featured: true,
    description: "A tailored conversational AI assistant engineered to answer queries regarding the Computer Science curriculum, subject prerequisites, and academic guidelines at NEMSU Lianga Campus.",
    tech: ["Python", "NLP", "Rule Engine", "Curriculum Knowledgebase", "CLI / Web UI"],
    githubUrl: "https://github.com/dxlmartin00/CS_Assistant",
    demoUrl: null,
    badge: "AI CHATBOT",
    icon: "🤖",
    highlights: ["NEMSU CS Curriculum Knowledge", "Prerequisite Navigator", "Natural Language Querying"]
  },
  {
    id: "smartqueue",
    title: "SmartQueue",
    category: "mobile",
    language: "Dart",
    stars: 0,
    featured: true,
    description: "A digital queueing and ticketing mobile app engineered with Flutter to streamline waiting lines in campus service windows, registrar offices, and student counters.",
    tech: ["Dart", "Flutter", "State Management", "Ticketing Algorithm", "Firebase"],
    githubUrl: "https://github.com/dxlmartin00/SmartQueue",
    demoUrl: null,
    badge: "MOBILE APP",
    icon: "🎟️",
    highlights: ["Virtual Queue Line Booking", "Estimated Wait Time Engine", "Live Status Updates"]
  },
  {
    id: "snapcite",
    title: "SnapCite",
    category: "mobile",
    language: "Dart",
    stars: 0,
    featured: false,
    description: "A mobile research companion built in Flutter allowing researchers and students to snap pictures of book pages or journal articles, extract text, and automatically format citations.",
    tech: ["Dart", "Flutter", "Camera API", "OCR Engine", "Citation Formatter"],
    githubUrl: "https://github.com/dxlmartin00/SnapCite",
    demoUrl: null,
    badge: "MOBILE / RESEARCH",
    icon: "📚",
    highlights: ["Camera Text Capture", "APA / MLA / Chicago Generator", "Reference Library Storage"]
  },
  {
    id: "easyocr-app",
    title: "EasyOCR-App",
    category: "ai",
    language: "Python",
    stars: 0,
    featured: false,
    description: "A desktop OCR utility leveraging Python and the EasyOCR deep learning library to extract multi-lingual printed and handwritten text from scanned documents with high accuracy.",
    tech: ["Python", "EasyOCR", "OpenCV", "PyTorch", "NumPy"],
    githubUrl: "https://github.com/dxlmartin00/EasyOCR-App",
    demoUrl: null,
    badge: "AI / OCR",
    icon: "👁️",
    highlights: ["Deep Learning Text Detection", "Preprocessing with OpenCV", "Batch Image Extraction"]
  },
  {
    id: "sentiment-analysis-m1",
    title: "Sentiment-Analysis-M1",
    category: "ai",
    language: "Python",
    stars: 0,
    featured: false,
    description: "Natural language processing machine learning pipeline trained to classify text reviews and social feedback into positive, neutral, or negative sentiment categories.",
    tech: ["Python", "Scikit-Learn", "NLTK / SpaCy", "Pandas", "Matplotlib"],
    githubUrl: "https://github.com/dxlmartin00/Sentiment-Analysis-M1",
    demoUrl: null,
    badge: "AI / NLP",
    icon: "💬",
    highlights: ["Text Preprocessing & Lemmatization", "TF-IDF Vectorization", "Classification Metrics"]
  },
  {
    id: "ocr-app",
    title: "OCR-App",
    category: "ai",
    language: "Python",
    stars: 1,
    featured: false,
    description: "Luigie's foundational computer vision project investigating image thresholding, binarization, and character segmentation pipelines for optical recognition.",
    tech: ["Python", "OpenCV", "Tesseract / PIL", "Image Filtering"],
    githubUrl: "https://github.com/dxlmartin00/OCR-App",
    demoUrl: null,
    badge: "FOUNDATIONAL CV",
    icon: "🔍",
    highlights: ["Image Thresholding & Contours", "Character Bounding Boxes", "First Computer Vision Build"]
  },
  {
    id: "module2-streamlitapp",
    title: "Module2-StreamlitApp",
    category: "ai",
    language: "Python",
    stars: 0,
    featured: false,
    description: "An interactive data science web application constructed using Python and Streamlit, providing rapid data profiling, interactive charts, and model inference widgets.",
    tech: ["Python", "Streamlit", "Pandas", "Seaborn", "Data Analytics"],
    githubUrl: "https://github.com/dxlmartin00/Module2-StreamlitApp",
    demoUrl: null,
    badge: "DATA APP",
    icon: "📈",
    highlights: ["Interactive Parameter Tuning", "Live Data Visualizations", "Instant Web Interface"]
  },
  {
    id: "react-express",
    title: "react-express",
    category: "web",
    language: "JavaScript",
    stars: 0,
    featured: false,
    description: "A robust fullstack web application template linking a modern modular React frontend to an Express.js backend with JSON REST endpoints and CORS security.",
    tech: ["React", "Node.js", "Express", "REST API", "JSON"],
    githubUrl: "https://github.com/dxlmartin00/react-express",
    demoUrl: null,
    badge: "FULLSTACK TEMPLATE",
    icon: "⚛️",
    highlights: ["React + Node Architecture", "Configured API Routes", "Production-ready Structure"]
  },
  {
    id: "martin-portfolio",
    title: "MARTIN_Portfolio",
    category: "web",
    language: "JavaScript",
    stars: 0,
    featured: false,
    description: "Luigie's earlier portfolio iteration built with web fundamentals and deployed to Vercel, showcasing the progression of design and frontend capabilities.",
    tech: ["JavaScript", "HTML5", "CSS3", "Vercel Deploy"],
    githubUrl: "https://github.com/dxlmartin00/MARTIN_Portfolio",
    demoUrl: "https://martin-portfolio-six.vercel.app",
    badge: "EARLY ITERATION",
    icon: "🌐",
    highlights: ["First Web Showcase", "Clean Responsive UI", "Deployed on Vercel"]
  }
];

if (typeof module !== "undefined" && module.exports) {
  module.exports = { PROJECTS_DATA };
}
